# Generated by Django 3.2.2 on 2022-02-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_artistprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistProfile',
        ),
    ]
