# Generated by Django 3.2.2 on 2023-05-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_delete_artistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artworks'),
        ),
    ]
