# Generated by Django 3.2.2 on 2023-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
