# Generated by Django 3.2.2 on 2021-06-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210526_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medium',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='orientation',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape'), ('S', 'Square')], default='P', max_length=2),
        ),
    ]
