# Generated by Django 3.2.2 on 2021-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210602_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('SL', 'Sale'), ('CL', 'Clearance'), ('NP', 'No Promotion')], default='NP', max_length=2),
        ),
    ]
