# Generated by Django 3.2.2 on 2021-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orientation',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('L', 'Landscape'), ('S', 'Square')], default='Portrait', max_length=254),
        ),
    ]
