# Generated by Django 3.2.2 on 2021-07-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='people',
            field=models.CharField(choices=[('With', 'With People'), ('Without', 'Without People')], default='With People', max_length=254),
        ),
    ]
