# Generated by Django 3.2.2 on 2021-07-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_category_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='people',
        ),
    ]
