# Generated by Django 3.2.2 on 2021-07-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
    ]
