# Generated by Django 3.2.2 on 2021-07-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210720_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('1', 'With People'), ('2', 'Without People'), ('3', 'Room for Copy'), ('4', 'Portrait'), ('5', 'Landscape'), ('6', 'Square')], default='1', max_length=254),
        ),
    ]
