# Generated by Django 3.2.2 on 2021-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
