# Generated by Django 3.2.2 on 2021-07-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_product_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_details',
        ),
    ]
