# Generated by Django 3.2.2 on 2021-07-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_product_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'parent')},
        ),
    ]
