# Generated by Django 3.2.2 on 2023-06-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_product_predicted_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
