# Generated by Django 3.2.2 on 2022-02-04 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_twitter_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('artist_behance_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('artist_instagram_handle', models.CharField(blank=True, max_length=20, null=True)),
                ('artist_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(default='avatar.jpg', upload_to='avatars')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
