from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile
# from django.contrib.auth.decorators import login_required
from .models import Profile
from .forms import ProfileForm
from django.contrib import messages
from checkout.models import Order, OrderItem
# import mindsdb config from settings.py
from django.conf import settings
import mindsdb_sdk
import openai
import pandas as pd
from pandas import DataFrame
from hugo.models import Artwork, Style
from shop.models import Product, Category

# mdb_server = mindsdb_sdk.connect(settings.MINDSDB_HOST, settings.MINDSDB_EMAIL, settings.MINDSDB_PASSWORD)
# project = mdb_server.get_project('mindsdb')

# response = openai.Image.create(
#   prompt="a purple siamese cat cartoon with a yellow background",
#   n=1,
#   size="1024x1024"
# )
# image_url = response['data'][0]['url']
# print(image_url)


# Create your views here.
def profile(request):
    """ 
    Display the user's profile 
    """
    profile = get_object_or_404(Profile, user=request.user)
    all_artworks = Artwork.objects.filter(user=request.user)
    for_sale_artworks = all_artworks.filter(for_sale=True)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Update failed. Please try again!')
    else:
        form = ProfileForm(instance=profile)
    orders = profile.orders.all()

    template = 'profiles/profile.html'
    context = {
        'form': form,
        'orders': orders,
        'on_profile_page': True,
        'all_artworks': all_artworks,
        'for_sale_artworks': for_sale_artworks,
    }

    return render(request, template, context)


def order_history(request, order_number):
    order = get_object_or_404(Order, order_number=order_number)
    orderitems = get_object_or_404(OrderItem, order=order)

    messages.info(request, (
        f'Your confirmation for order number # {order_number} was sent to {order.email} on {order.created_at}.'
    ))

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
        'from_profile': True,
        'orderitems': orderitems,
    }

    return render(request, template, context)


def artworkGenerated(request, artwork_id):
    """
    A view to render a user's artwork generated by the AI on their profile page
    """
    profile = get_object_or_404(Profile, user=request.user)
    user = profile.user
    artworks = get_object_or_404(Artwork, artwork_id=artwork_id)
    
    template = 'profiles/artwork.html'
    context = {
        'artworks': artworks,
        'artwork_id': artwork_id,
        'user': user,
    }

    return render(request, template, context)


def user_profile(request, username):
    user_profile = get_object_or_404(Profile, user__username=username)
    artworks = Artwork.objects.filter(user=user_profile.user)
    
    return render(request, 'profiles/user_profile.html', {'user_profile': user_profile, 'artworks': artworks})