# Generated by Django 3.2.2 on 2021-06-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210604_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orientation',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape'), ('S', 'Square')], default='Portrait', max_length=2),
        ),
    ]
