# Generated by Django 3.2.2 on 2021-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_dimensions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='orientation',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape'), ('Square', 'Square')], default='Portrait', max_length=254),
        ),
    ]
