# Generated by Django 3.2.2 on 2021-07-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210718_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
