# Generated by Django 3.2.2 on 2021-07-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_category_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(choices=[('With', 'With People'), ('Without', 'Without People')], default='Without People', max_length=254),
        ),
    ]
