# Generated by Django 3.2.2 on 2021-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210720_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('1', 'With People'), ('2', 'Without People')], default='1', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='orientation',
            field=models.CharField(choices=[('3', 'Portrait'), ('4', 'Landscape'), ('5', 'Square')], default='3', max_length=254),
        ),
    ]
