# Generated by Django 3.2.2 on 2021-07-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
    ]
