# Generated by Django 3.2.2 on 2022-02-05 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0033_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('orientation', models.CharField(choices=[('3', 'Portrait'), ('4', 'Landscape'), ('5', 'Square')], default='3', max_length=254)),
                ('label', models.CharField(choices=[('1', 'With People'), ('2', 'Without People')], default='1', max_length=254)),
                ('has_dimensions', models.BooleanField(blank=True, default=False, null=True)),
                ('medium', models.CharField(blank=True, max_length=254)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
