# Generated by Django 3.2.2 on 2023-04-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_product_artwork_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
