# Generated by Django 3.2.2 on 2023-08-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='predicted_titles',
        ),
    ]
