# Generated by Django 3.2.2 on 2023-08-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_product_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
    ]
