# Generated by Django 3.2.2 on 2023-08-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0007_auto_20230808_2044'),
        ('shop', '0041_remove_product_predicted_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aiArt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hugo.artwork'),
        ),
    ]
