# Generated by Django 3.2.2 on 2023-08-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0008_artwork_price'),
        ('shop', '0042_remove_product_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='hugo.style'),
        ),
    ]
