# Generated by Django 3.2.2 on 2023-05-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hugo',
            name='artwork',
        ),
    ]
