# Generated by Django 3.2.2 on 2023-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0002_remove_hugo_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='hugo',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artworks'),
        ),
        migrations.AddField(
            model_name='hugo',
            name='artworkImage',
            field=models.FileField(blank=True, null=True, upload_to='artworks'),
        ),
    ]
