# Generated by Django 3.2.2 on 2023-06-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0002_artwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hugo',
        ),
    ]
