# Generated by Django 3.2.2 on 2023-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0003_auto_20230525_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hugo',
            name='artworkImage',
        ),
        migrations.AddField(
            model_name='hugo',
            name='genArt',
            field=models.ImageField(default='banana.png', upload_to='artworks'),
        ),
    ]
