# Generated by Django 3.2.2 on 2023-08-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_product_seller'),
        ('hugo', '0004_auto_20230630_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
