# Generated by Django 3.2.2 on 2023-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0005_artwork_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
