# Generated by Django 3.2.2 on 2023-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0005_artwork_is_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
