# Generated by Django 3.2.2 on 2023-08-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0006_artwork_for_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='product',
        ),
        migrations.AddField(
            model_name='artwork',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
