# Generated by Django 3.2.2 on 2023-08-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0006_artwork_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
