# Generated by Django 3.2.2 on 2023-08-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0007_artwork_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
