# Generated by Django 3.2.2 on 2022-02-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20220204_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistinfo',
            name='user',
        ),
    ]
